# Generated by Django 3.1.2 on 2020-10-29 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_vendor',
            field=models.BooleanField(default=False, verbose_name='Представитель поставщика'),
        ),
    ]
