# Generated by Django 3.1.2 on 2020-10-28 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='additionalgoodparameter',
            options={'verbose_name': 'Параметр', 'verbose_name_plural': 'Параметры'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='good',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='shop',
            options={'verbose_name': 'Поставщик', 'verbose_name_plural': 'Поставщики'},
        ),
        migrations.AlterField(
            model_name='additionalgoodparameter',
            name='good',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='additional_parameters', to='orders.good', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='additionalgoodparameter',
            name='parameter',
            field=models.CharField(max_length=50, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='additionalgoodparameter',
            name='value',
            field=models.CharField(max_length=50, verbose_name='Значение'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='good',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='good',
            name='model',
            field=models.CharField(max_length=50, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='good',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='good',
            name='price',
            field=models.PositiveIntegerField(verbose_name='Оптовая цена'),
        ),
        migrations.AlterField(
            model_name='good',
            name='price_rrc',
            field=models.PositiveIntegerField(verbose_name='Розничная цена'),
        ),
        migrations.AlterField(
            model_name='good',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='good',
            name='shops',
            field=models.ManyToManyField(related_name='shops', to='orders.Shop', verbose_name='Поставщик'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Статус'),
        ),
    ]
